/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        ARDUINOOTTOROBOT_CATEGORY: 'Otto',
        otto_initPins: 'Pins Leg left %1 right %2 Foot left %3 right %4 Buzzer %5',
        otto_home: 'Home',
        otto_move: 'Move %1 Speed %2',
        move_forward: 'forward',
        move_backward: 'backward',
        move_turnleft: 'turn left',
        move_turnright: 'turn right',
        move_bendleft: 'bend to the left',
        move_bendright: 'bend to the right',
        move_shakeleft: 'shake left leg',
        move_shakeright: 'shake right leg',
        move_up: 'up',
        speed_normal: 'normal',
        speed_slow: 'slow',
        speed_veryslow: 'very slow',
        speed_fast: 'fast',
        speed_veryfast: 'very fast',
        speed_waytofast: 'way to fast',
        otto_dance: 'Dance %1 Speed %2 Size %3',
        dance_moonwalkleft: 'moonwalk ←',
        dance_moonwalkright: 'moonwalk →',
        dance_crossingleft: 'crossing ←',
        dance_crossingright: 'crossing →',
        dance_flappingup: 'flapping ↑',
        dance_flappingdown: 'flapping ↓',
        size_normal: 'normal',
        size_little: 'little',
        size_big: 'big',
        otto_do_behavior: 'Do %1 Speed %2 Size %3',
        do_swing: 'swing',
        do_updown: 'updown',
        do_tiptoeSwing: 'tiptoeSwing',
        do_jitter: 'jitter',
        do_ascendingTurn: 'scendingTurn',
        otto_do_gesture: 'Gesture %1'
        // gesture_OttoSuperHappy: 'happy1',
        // gesture_OttoHappy: 'happy2',
        // gesture_OttoSad: 'sad',
        // gesture_OttoSleeping: 'sleep',
        // gesture_OttoConfused: 'confused',
        // gesture_OttoFretful: 'fretful',
        // gesture_OttoLove: 'love',
        // gesture_OttoAngry: 'angry',
        // gesture_OttoMagic: 'magic',
        // gesture_OttoWave: 'wave',
        // gesture_OttoVictory: 'victory',
        // gesture_OttoFail: 'fail',
        // gesture_OttoFart: 'fart'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        ARDUINOOTTOROBOT_CATEGORY: 'Otto',
        otto_initPins: '引脚 左腿 %1 右腿 %2 左脚 %3 右脚 %4 喇叭 %5',
        otto_home: '回归中立位置',
        otto_move: '移动 %1 速度 %2',
        move_forward: '前进',
        move_backward: '后退',
        move_turnleft: '左转',
        move_turnright: '右转',
        move_bendleft: '向左转',
        move_bendright: '向右转',
        move_shakeleft: '摇晃左腿',
        move_shakeright: '摇晃右腿',
        move_up: '向上',
        speed_normal: '常规',
        speed_slow: '慢',
        speed_veryslow: '很慢',
        speed_fast: '快',
        speed_veryfast: '很快',
        speed_waytofast: '快速的方式',
        otto_dance: '跳舞 %1 速度 %2 幅度 %3',
        dance_moonwalkleft: '漫步 ←',
        dance_moonwalkright: '漫步 →',
        dance_crossingleft: '横渡 ←',
        dance_crossingright: '横渡 →',
        dance_flappingup: '摇摆 ↑',
        dance_flappingdown: '摇摆 ↓',
        size_normal: '常规',
        size_little: '小',
        size_big: '大',
        otto_do_behavior: '做 %1 速度 %2 幅度 %3',
        do_swing: '摇摆',
        do_updown: '上下',
        do_tiptoeSwing: '脚尖摇摆',
        do_jitter: '抖动',
        do_ascendingTurn: '左右摇晃转',
        otto_do_gesture: '姿态 %1'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-tw'], {
        ARDUINOOTTOROBOT_CATEGORY: 'Otto',
        otto_initPins: '引腳 左腿 %1 右腿 %2 左腳 %3 右腳 %4 喇叭 %5',
        otto_home: '回歸中立位置',
        otto_move: '移動 %1 速度 %2',
        move_forward: '前進',
        move_backward: '後退',
        move_turnleft: '左轉',
        move_turnright: '右轉',
        move_bendleft: '向左轉',
        move_bendright: '向右轉',
        move_shakeleft: '搖晃左腿',
        move_shakeright: '搖晃右腿',
        move_up: '向上',
        speed_normal: '常規',
        speed_slow: '慢',
        speed_veryslow: '很慢',
        speed_fast: '快',
        speed_veryfast: '很快',
        speed_waytofast: '快速的方式',
        otto_dance: '跳舞 %1 速度 %2 幅度 %3',
        dance_moonwalkleft: '漫步 ←',
        dance_moonwalkright: '漫步 →',
        dance_crossingleft: '橫渡 ←',
        dance_crossingright: '橫渡 →',
        dance_flappingup: '搖擺 ↑',
        dance_flappingdown: '搖擺 ↓',
        size_normal: '常規',
        size_little: '小',
        size_big: '大',
        otto_do_behavior: '做 %1 速度 %2 幅度 %3',
        do_swing: '搖擺',
        do_updown: '上下',
        do_tiptoeSwing: '腳尖搖擺',
        do_jitter: '抖動',
        do_ascendingTurn: '左右搖晃轉',
        otto_do_gesture: '姿態 %1'
    });
    return Blockly;
}

exports = addMsg;
